services:
  _defaults:
    autowire: true
    autoconfigure: true

  App\Tests\Scenario\Context\APIContext:
    public: true
    arguments:
      - http://localhost:8003/v1
      - "@service_container"


